artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion  # folder
  source_URL: https://github.com/Gurdeepsingh96/branching_tutorial/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

